// Question id -> prompt text, for display purposes only (teacher dashboard). Mirrors the
// QUESTIONS / QUESTIONS_1_2 / COMPREHENSION_QUESTIONS / COMPREHENSION_QUESTIONS_1_2 arrays
// in components/BizQuest.js. If those question banks change (new/edited/removed
// questions), update this file to match, or the dashboard will fall back to showing raw
// ids for anything not listed here.
export const QUESTION_BANK = {
  "1.1": {
    v1: "Define the term business.",
    v2: "Define the term primary sector.",
    v3: "Define the term secondary sector.",
    v4: "Define the term tertiary sector.",
    v5: "Define the term quaternary sector.",
    v6: "Define the term entrepreneur.",
    v7: "Define the term entrepreneurship.",
    s8: "State two sectors of the economy in which Apple operates.",
    s9: "Describe two reasons why Jobs and Wozniak can be considered entrepreneurs.",
    s10: "Explain two reasons why Apple's growing Services revenue represents a shift toward the tertiary and quaternary sectors.",
    c1: "According to the video, where did Steve Wozniak first meet Steve Jobs?",
    c2: "According to the video, what did Wozniak actually build, and what did Jobs propose doing with it?",
  },
  "1.2": {
    v1: "Define the term private sector.",
    v2: "Define the term public sector.",
    v3: "Define the term sole trader.",
    v4: "Define the term partnership.",
    v5: "Define the term unlimited liability.",
    v6: "Define the term limited liability.",
    v7: "Define the term incorporation.",
    v8: "Define the term privately held company.",
    v9: "Define the term publicly held company.",
    v10: "Define the term for-profit social enterprise.",
    v13: "Define the term cooperative.",
    v14: "Define the term NGO / non-profit social enterprise.",
    v15: "Define the term deed of partnership.",
    v16: "Define the term shareholder.",
    s17: "State two features of a general partnership.",
    s18: "Describe one advantage and one disadvantage of unlimited liability for a business owner.",
    s19: "Explain two advantages Apple gained by converting from a partnership into an incorporated, publicly held company.",
    e21: "Discuss whether Apple's move from a partnership to an incorporated, publicly held company was the right strategic choice for the business.",
    c1: "According to the video, how did Phil Knight and Bill Bowerman start their business, and what was it originally called?",
    c2: "According to the video, what did Blue Ribbon Sports do in its earliest days, before it made its own shoes?",
  },
  "1.3": {
    v1: "Define the term vision statement.",
    v2: "Define the term mission statement.",
    v3: "Define the term business objectives.",
    v4: "Define the term SMART objectives.",
    v5: "Define the term strategic objectives.",
    v6: "Define the term tactical objectives.",
    v7: "Define the term corporate social responsibility (CSR).",
    s8: "State two of Apple's official corporate values.",
    s9: "Describe two of Apple's financial objectives for FY2025.",
    s10: "Explain two reasons why Apple's ethical objectives might conflict with its financial objectives.",
    e11: "Evaluate the extent to which Apple's stated ethical and environmental objectives are compatible with its objective of maximizing shareholder returns.",
    c1: "According to the video, what did Theranos claim its technology could do?",
    c2: "What eventually happened to the company and its leadership?",
  },
  "1.4": {
    v1: "Define the term stakeholder.",
    v2: "Define the term internal stakeholder.",
    v3: "Define the term external stakeholder.",
    v4: "Define the term pressure group.",
    v5: "Define the term financier.",
    v6: "Define the term stakeholder conflict.",
    v7: "Define the term stakeholder mapping.",
    s8: "State two external stakeholders of Apple mentioned in the case study.",
    s9: "Describe one of Apple's internal stakeholders and one of Apple's external stakeholders.",
    s10: "Explain two reasons why shareholders and environmental groups might have conflicting interests in relation to Apple.",
    s11: "Using stakeholder mapping, classify two of Apple's stakeholders from the case study by their likely level of interest and power, and justify your classification.",
    e12: "Discuss whether Apple's various stakeholder conflicts suggest the company would better serve its stakeholders under a different business entity structure than a publicly held company.",
    c1: "According to the video, what employment entitlements were drivers seeking from Uber and Lyft?",
    c2: "Why might Uber and Lyft resist classifying drivers as employees rather than independent contractors?",
  },
  "1.5": {
    v1: "Define the term internal (organic) growth.",
    v2: "Define the term external growth.",
    v3: "Define the term economies of scale.",
    v4: "Define the term internal economies of scale.",
    v5: "Define the term external economies of scale.",
    v6: "Define the term diseconomies of scale.",
    v7: "Define the term merger and acquisition.",
    v8: "Define the term takeover.",
    v9: "Define the term joint venture.",
    v10: "Define the term strategic alliance.",
    v11: "Define the term franchising.",
    s12: "State two methods of external growth that Apple has avoided using.",
    s13: "Describe two of Apple's acquisitions, other than Beats Electronics.",
    s14: "Explain two reasons why Apple's expansion of overlapping Macintosh models in the mid-1990s illustrates the concept of diseconomies of scale.",
    s15: "At a 2021 shareholder meeting, Tim Cook stated that Apple had acquired close to 100 companies over the previous six years — roughly one every two to three weeks. Calculate the minimum and maximum number of companies Apple could have acquired over six years at this rate (show all your working).",
    e16: "To what extent has Apple's growth strategy of pursuing small, technology-focused acquisitions been effective?",
    c1: "According to the interview, what did Jobs say was his strategy for turning Apple around?",
    c2: "According to the interview, how did the crowd react when Jobs announced Apple's new partnership with Microsoft at Macworld?",
  },
  "1.6": {
    v1: "Define the term multinational company (MNC).",
    v2: "Define the term host country.",
    v3: "Define the term home country.",
    v4: "Define the term offshoring.",
    v5: "Define the term reshoring.",
    v6: "Define the term repatriation of profits.",
    v7: "Define the term protectionism.",
    s8: "State two host countries, other than the United States, mentioned in the case study.",
    s9: "Describe one potential benefit and one potential drawback for China, as a host country, resulting from Apple's manufacturing decisions.",
    s10: "Explain two reasons why Apple has diversified its manufacturing base away from China.",
    s11: "Using the case study, calculate the percentage point increase in India's share of global iPhone production between 2022 (5–7%) and late 2024 (15%).",
    e12: "Evaluate the impact of Apple's shift of manufacturing away from China and toward India on stakeholders in each country.",
    c1: "According to the video, why is Apple shifting iPhone assembly toward India?",
    c2: "According to the video, by when is Apple aiming to assemble all US-bound iPhones in India?",
  },
};

// Looks up prompt text, falling back to the raw id if a question isn't in the bank
// (e.g. content added to BizQuest.js after this file was last synced).
export function questionText(subunitId, questionId) {
  return QUESTION_BANK[subunitId]?.[questionId] || questionId;
}
